export const songs: { artist: string; title: string }[] = [
  { artist: 'George Ezra', title: 'Budapest' },
  { artist: 'Rick Astley', title: 'Never Gonna Give You Up' },
  { artist: 'Queen', title: 'Bohemian Rhapsody' },
  { artist: 'Adele', title: 'Rolling in the Deep' },
  { artist: 'Billie Eilish', title: 'bad guy' },
  { artist: 'The Weeknd', title: 'Blinding Lights' },
  { artist: 'Dua Lipa', title: 'Levitating' },
  { artist: 'Harry Styles', title: 'As It Was' },
  { artist: 'Ed Sheeran', title: 'Shape of You' },
  { artist: 'Taylor Swift', title: 'Blank Space' },
  { artist: 'Bruno Mars', title: 'Uptown Funk' },
  { artist: 'Mark Ronson', title: 'Uptown Funk' },
  { artist: 'Whitney Houston', title: 'I Wanna Dance with Somebody' },
  { artist: 'Michael Jackson', title: 'Billie Jean' },
  { artist: 'Nirvana', title: 'Smells Like Teen Spirit' },
  { artist: 'Oasis', title: 'Wonderwall' },
  { artist: 'Coldplay', title: 'Yellow' },
  { artist: 'Radiohead', title: 'Creep' },
  { artist: 'Red Hot Chili Peppers', title: 'Californication' },
  { artist: 'Foo Fighters', title: 'Everlong' },
  { artist: 'Linkin Park', title: 'In the End' },
  { artist: 'Eminem', title: 'Lose Yourself' },
  { artist: 'Kendrick Lamar', title: 'HUMBLE.' },
  { artist: 'Drake', title: 'Hotline Bling' },
  { artist: 'Beyoncé', title: 'Halo' },
  { artist: 'Rihanna', title: 'Umbrella' },
  { artist: 'Lady Gaga', title: 'Bad Romance' },
  { artist: 'Katy Perry', title: 'Firework' },
  { artist: 'Britney Spears', title: 'Toxic' },
  { artist: 'Madonna', title: 'Like a Prayer' },
  { artist: 'ABBA', title: 'Dancing Queen' },
  { artist: 'Fleetwood Mac', title: 'Dreams' },
  { artist: 'Eagles', title: 'Hotel California' },
  { artist: 'Journey', title: "Don't Stop Believin'" },
  { artist: 'Bon Jovi', title: "Livin' on a Prayer" },
  { artist: "Guns N' Roses", title: "Sweet Child O' Mine" },
  { artist: 'AC/DC', title: 'Back in Black' },
  { artist: 'Led Zeppelin', title: 'Stairway to Heaven' },
  { artist: 'The Beatles', title: 'Hey Jude' },
  { artist: 'Elton John', title: 'Rocket Man' },
  { artist: 'David Bowie', title: 'Heroes' },
  { artist: 'Prince', title: 'Purple Rain' },
  { artist: 'Stevie Wonder', title: 'Superstition' },
  { artist: 'Aretha Franklin', title: 'Respect' },
  { artist: 'Bob Marley', title: 'Three Little Birds' },
  { artist: 'John Legend', title: 'All of Me' },
  { artist: 'Sam Smith', title: 'Stay With Me' },
  { artist: 'Lewis Capaldi', title: 'Someone You Loved' },
  { artist: 'Shawn Mendes', title: 'Stitches' },
  { artist: 'Olivia Rodrigo', title: 'drivers license' },
  { artist: 'Doja Cat', title: 'Say So' },
  { artist: 'Lizzo', title: 'About Damn Time' },
  { artist: 'SZA', title: 'Kill Bill' },
  { artist: 'Post Malone', title: 'Circles' },
  { artist: 'Imagine Dragons', title: 'Believer' },
  { artist: 'OneRepublic', title: 'Counting Stars' },
  { artist: 'Maroon 5', title: 'Sugar' },
  { artist: 'Justin Bieber', title: 'Sorry' },
  { artist: 'Ariana Grande', title: '7 rings' },
  { artist: 'Selena Gomez', title: 'Lose You to Love Me' },
  { artist: 'Miley Cyrus', title: 'Flowers' },
  { artist: 'Sia', title: 'Chandelier' },
  { artist: 'Lorde', title: 'Royals' },
  { artist: 'Hozier', title: 'Take Me to Church' },
  { artist: 'Vance Joy', title: 'Riptide' },
  { artist: 'Passenger', title: 'Let Her Go' },
  { artist: 'Gotye', title: 'Somebody That I Used to Know' },
  { artist: 'fun.', title: 'We Are Young' },
  { artist: 'Foster the People', title: 'Pumped Up Kicks' },
  { artist: 'MGMT', title: 'Electric Feel' },
  { artist: 'Tame Impala', title: 'The Less I Know the Better' },
  { artist: 'Arctic Monkeys', title: 'Do I Wanna Know?' },
  { artist: 'The Killers', title: 'Mr. Brightside' },
  { artist: 'Kings of Leon', title: 'Use Somebody' },
  { artist: 'Snow Patrol', title: 'Chasing Cars' },
  { artist: 'Keane', title: 'Somewhere Only We Know' },
  { artist: 'The Script', title: 'Breakeven' },
  { artist: 'James Arthur', title: 'Say You Won\'t Let Go' },
  { artist: 'Calum Scott', title: 'Dancing On My Own' },
  { artist: 'Rag\'n\'Bone Man', title: 'Human' },
  { artist: 'James Bay', title: 'Hold Back the River' },
  { artist: 'Tom Odell', title: 'Another Love' },
  { artist: 'Alicia Keys', title: 'If I Ain\'t Got You' },
  { artist: 'Norah Jones', title: 'Don\'t Know Why' },
  { artist: 'Amy Winehouse', title: 'Rehab' },
  { artist: 'Adele', title: 'Someone Like You' },
  { artist: 'Sam Cooke', title: 'A Change Is Gonna Come' },
  { artist: 'Otis Redding', title: '(Sittin\' On) The Dock of the Bay' },
  { artist: 'Marvin Gaye', title: 'What\'s Going On' },
  { artist: 'Al Green', title: 'Let\'s Stay Together' },
  { artist: 'Bill Withers', title: 'Ain\'t No Sunshine' },
  { artist: 'Johnny Cash', title: 'Hurt' },
  { artist: 'Dolly Parton', title: 'Jolene' },
  { artist: 'Shania Twain', title: 'Man! I Feel Like a Woman!' },
  { artist: 'Carrie Underwood', title: 'Before He Cheats' },
  { artist: 'Taylor Swift', title: 'Love Story' },
  { artist: 'Ed Sheeran', title: 'Perfect' },
  { artist: 'Shawn Mendes', title: 'Treat You Better' },
  { artist: 'Charlie Puth', title: 'Attention' },
  { artist: 'The Chainsmokers', title: 'Closer' },
  { artist: 'Marshmello', title: 'Happier' },
  { artist: 'Avicii', title: 'Wake Me Up' },
  { artist: 'Calvin Harris', title: 'Summer' },
  { artist: 'David Guetta', title: 'Titanium' },
  { artist: 'Daft Punk', title: 'Get Lucky' },
];
